// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApARqxCpD2R181YvHroVRso9a8P6Qjbdw',
    appId: '1:255007071861:web:a579f467b1d1a59069e23c',
    messagingSenderId: '255007071861',
    projectId: 'focusnflow-dcdef',
    authDomain: 'focusnflow-dcdef.firebaseapp.com',
    storageBucket: 'focusnflow-dcdef.firebasestorage.app',
    measurementId: 'G-W139FYE8EC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzYPZ1OK_hTE6_HZBbmOSNkfHaRoUIcUA',
    appId: '1:255007071861:android:3ac9905e0f1bda6969e23c',
    messagingSenderId: '255007071861',
    projectId: 'focusnflow-dcdef',
    storageBucket: 'focusnflow-dcdef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAsibiMTWDmNck2qIbGVdzk8FnXLaWb7c',
    appId: '1:255007071861:ios:288f7216a4b4e7cc69e23c',
    messagingSenderId: '255007071861',
    projectId: 'focusnflow-dcdef',
    storageBucket: 'focusnflow-dcdef.firebasestorage.app',
    iosBundleId: 'com.example.focusnflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAsibiMTWDmNck2qIbGVdzk8FnXLaWb7c',
    appId: '1:255007071861:ios:288f7216a4b4e7cc69e23c',
    messagingSenderId: '255007071861',
    projectId: 'focusnflow-dcdef',
    storageBucket: 'focusnflow-dcdef.firebasestorage.app',
    iosBundleId: 'com.example.focusnflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApARqxCpD2R181YvHroVRso9a8P6Qjbdw',
    appId: '1:255007071861:web:d9759b955cee4a7669e23c',
    messagingSenderId: '255007071861',
    projectId: 'focusnflow-dcdef',
    authDomain: 'focusnflow-dcdef.firebaseapp.com',
    storageBucket: 'focusnflow-dcdef.firebasestorage.app',
    measurementId: 'G-6HM544QYPN',
  );
}
